/**
 * Canonical contract/address configuration — the SINGLE module every read,
 * write, and display of a contract address flows through (§14.2 phishing
 * resistance / address pinning).
 *
 * - The target environment is pinned at BUILD time via NEXT_PUBLIC_CHAIN
 *   ("local" [default], "sepolia", "robinhood", or "mainnet"); the chain id is
 *   pinned per environment (local 31337, sepolia 11155111, robinhood 4663,
 *   mainnet 1) and the app refuses writes on any other chain.
 * - Addresses come from the per-environment JSON. addresses.local.json is
 *   GENERATED by `scripts/gen-addresses.mjs local` from the deploy broadcast;
 *   addresses.sepolia.json / addresses.mainnet.json hold UNSET sentinels until
 *   their deployments exist (generated the same way with the network arg). We
 *   never fake an address.
 * - Every address is checksum-normalized (viem `getAddress`) at module load;
 *   a malformed or UNSET address in the SELECTED environment throws at build /
 *   first import rather than shipping a wrong address. (Non-selected
 *   environments' UNSET files never load, so the app builds before those
 *   deploys exist.)
 */
import { getAddress, type Address } from "viem";
import localJson from "./addresses.local.json";
import sepoliaJson from "./addresses.sepolia.json";
import robinhoodJson from "./addresses.robinhood.json";
import mainnetJson from "./addresses.mainnet.json";

export type ChainEnvName = "local" | "sepolia" | "robinhood" | "mainnet";

export type ContractName =
  | "cardsToken"
  | "cardsOnChain"
  | "stakingVault"
  | "cardYield"
  | "cardArt"
  | "cardRenderer"
  /** The router users sign trades through: Uniswap's UniversalRouter (official
   *  deployment on live networks; a V4Router-core stand-in on local). Resolved
   *  from the hook's immutable `router()` by gen-addresses. */
  | "swapRouter"
  /** QUOTE-ONLY PoolSwapTest: used exclusively inside eth_call simulations to
   *  learn expected fills (lib/chain/quote.ts). Never signed, never holds funds. */
  | "quoteSim"
  | "lpRouter"
  | "mintHook"
  | "poolManager";

export interface ChainEnvironment {
  name: ChainEnvName;
  chainId: number;
  /** Block the system was deployed at — start of all event scans. */
  deploymentBlock: bigint;
  contracts: Record<ContractName, Address>;
}

/** Per-environment address JSON (untyped shape from disk). */
const ADDRESS_JSON: Record<ChainEnvName, { chainId: number; deploymentBlock: number; contracts: Record<string, string> }> = {
  local: localJson,
  sepolia: sepoliaJson,
  robinhood: robinhoodJson,
  mainnet: mainnetJson,
};

/**
 * Build-time environment pin (NEXT_PUBLIC_CHAIN, inlined at build).
 *
 * Default is **robinhood** — the launch chain for the Forged Cards relaunch
 * (owner decision 2026-07-09: Robinhood Chain is drawing liquidity). A
 * production host (Vercel/Netlify/etc.) runs a plain `next build` and does NOT
 * set NEXT_PUBLIC_CHAIN, so the default is what ships. Every other environment
 * must be EXPLICIT: `npm run dev:local` / `dev:sepolia` / `dev:mainnet` (each
 * sets the var). NOTE: re-sync addresses.robinhood.json from the RELAUNCH deploy
 * before pushing — the file still holds the old (renounced) deployment until
 * `sync:addresses -- --network robinhood` runs against the new one.
 */
export const CHAIN_ENV: ChainEnvName =
  process.env.NEXT_PUBLIC_CHAIN === "mainnet"
    ? "mainnet"
    : process.env.NEXT_PUBLIC_CHAIN === "sepolia"
      ? "sepolia"
      : process.env.NEXT_PUBLIC_CHAIN === "local"
        ? "local"
        : "robinhood";

function load(name: ChainEnvName): ChainEnvironment {
  const raw = ADDRESS_JSON[name];
  const contracts = {} as Record<ContractName, Address>;
  for (const [key, value] of Object.entries(raw.contracts)) {
    if (value === "UNSET") {
      throw new Error(
        `contracts/addresses.${name}.json: "${key}" is UNSET — the ${name} deployment is not wired yet. ` +
          `Refusing to build with placeholder addresses.`,
      );
    }
    // getAddress checksums AND validates; throws on any malformed address.
    contracts[key as ContractName] = getAddress(value);
  }
  return {
    name,
    chainId: raw.chainId,
    deploymentBlock: BigInt(raw.deploymentBlock),
    contracts,
  };
}

export const ENV: ChainEnvironment = load(CHAIN_ENV);

/** Checksummed canonical address of a contract in the pinned environment. */
export const addressOf = (name: ContractName): Address => ENV.contracts[name];

/**
 * LPLocker (the launch liquidity time-lock) — OPTIONAL: it deploys in the LOCK
 * step after the main deployment (script/LockLP.s.sol), so it is absent until
 * `sync:addresses` runs post-lock. Null = not locked/wired yet; the footer
 * simply omits the row. Never UNSET-gated — a missing locker must not block
 * builds of pre-lock environments (local/sepolia rehearsals).
 */
const rawLpLocker = (ADDRESS_JSON[CHAIN_ENV].contracts as Record<string, string>).lpLocker;
export const lpLockerAddress: Address | null =
  rawLpLocker && rawLpLocker !== "UNSET" ? getAddress(rawLpLocker) : null;

/**
 * Uniswap periphery addresses (PositionManager + Permit2) per network — protocol
 * constants, NOT part of our deployment, so they live here rather than in the
 * generated address JSON. Used by the Liquidity tab (add/remove LP positions).
 * Permit2 is the same canonical address on every chain. `local` is a placeholder
 * (the Liquidity tab targets live networks). Sourced from the same verified
 * addresses used by the deploy driver / Deploy.s.sol.
 */
const ZERO_ADDR = "0x0000000000000000000000000000000000000000";
const PERIPHERY: Record<ChainEnvName, { positionManager: string; permit2: string }> = {
  local: { positionManager: ZERO_ADDR, permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3" },
  sepolia: {
    positionManager: "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  },
  robinhood: {
    // Official Robinhood Chain (4663) V4 periphery — docs.uniswap.org/contracts/v4/deployments,
    // verified 2026-07-09; code-existence fork-proven by test/fork/RobinhoodFork.t.sol.
    positionManager: "0x58daec3116aae6D93017bAAea7749052E8a04fA7",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  },
  mainnet: {
    positionManager: "0xbD216513d74C8cf14cf4747E6AaA6420FF64ee9e",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  },
};

/** Canonical Uniswap PositionManager for the pinned network (LP add/remove). */
export const positionManagerAddress: Address = getAddress(PERIPHERY[CHAIN_ENV].positionManager);
/** Canonical Permit2 for the pinned network (PositionManager pulls FORGE via it). */
export const permit2Address: Address = getAddress(PERIPHERY[CHAIN_ENV].permit2);

/**
 * UniversalRouter ABI dialect. Robinhood Chain's UniversalRouter is a CUSTOMIZED
 * build whose ExactInputSingleParams struct carries an extra `minHopPriceX36`
 * field (verified against its Blockscout-verified source, 2026-07-09). True →
 * lib/chain/swap.ts encodes the 6-field variant; false → the standard Uniswap
 * 5-field struct (mainnet / Sepolia / the local V4Router stand-in).
 */
export const urHopPricedParams: boolean = CHAIN_ENV === "robinhood";

/**
 * How sells hand FORGE to the router. The real UniversalRouter pulls the input
 * token through Permit2 (approve token→Permit2, then Permit2→router); the local
 * stand-in pulls with a plain `transferFrom` (no Permit2 exists on a fresh
 * local chain), so local approves the router directly.
 */
export const sellsViaPermit2: boolean = CHAIN_ENV !== "local";

/** The only chain id the app will ever write to. */
export const PINNED_CHAIN_ID = ENV.chainId;

/** Human-readable name of the pinned chain, for display copy (hero badge etc.). */
export const CHAIN_LABEL: string = {
  local: "Local devnet",
  sepolia: "Sepolia testnet",
  robinhood: "Robinhood Chain",
  mainnet: "Ethereum mainnet",
}[CHAIN_ENV];

/**
 * Default read RPC per chain when NEXT_PUBLIC_RPC_URLS is not set — public,
 * keyless endpoints safe to embed, so a plain production build reads the chain
 * with zero host config (and the CSP in next.config.mjs allows the same
 * origins). Mainnet lists two independent public providers; the client's
 * fallback transport ranks them and fails over automatically. Override with
 * NEXT_PUBLIC_RPC_URLS for a dedicated endpoint. MUST stay in sync with
 * next.config.mjs's `DEFAULT_RPC`.
 */
const DEFAULT_RPC: Record<ChainEnvName, string> = {
  local: "http://127.0.0.1:8545",
  // Public keyless Sepolia endpoint: the safe fallback a BUILD uses when the
  // .env RPC is a private/keyed endpoint (run-next.mjs refuses to embed those).
  sepolia: "https://ethereum-sepolia-rpc.publicnode.com",
  robinhood: "https://rpc.mainnet.chain.robinhood.com",
  mainnet: "https://ethereum-rpc.publicnode.com,https://eth.llamarpc.com",
};

/**
 * RPC endpoints (reads / fallback transport). Wallet writes go through the
 * wallet's own provider; these are for the public client only. Set
 * NEXT_PUBLIC_RPC_URLS (comma-separated) to override the per-chain default.
 */
export const RPC_URLS: string[] = (process.env.NEXT_PUBLIC_RPC_URLS ?? DEFAULT_RPC[CHAIN_ENV])
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

/** getLogs chunk size for event scans (public RPCs cap ranges; local doesn't). */
export const LOG_CHUNK: bigint = BigInt(
  process.env.NEXT_PUBLIC_LOG_CHUNK ?? (CHAIN_ENV === "local" ? "0" : "9000"),
); // 0 = unchunked (single range)
