#!/usr/bin/env node
/**
 * verify-flows.mjs — end-to-end flow verification harness (§14.2 definition of
 * done). Drives viem against a LOCAL anvil deployment of the real contracts,
 * exercising the SAME call paths the UI signs:
 *
 *   1. buy WITH hookData=abi.encode(recipient)  → mints cards to that recipient
 *   1b. buy WITHOUT hookData                     → mints to tx.origin (the
 *       signer) via the contract's fallback; confirms why we still always pass
 *       the explicit address (exact attribution for SC-wallet users)
 *   2. sell                                      → CardYield receives the fee
 *   3. stake / unstake                           → free-stake accounting
 *   4. forge → warp (evm_increaseTime+evm_mine) → claim   (tier changes)
 *   5. forge → lapse past claim window → sweep   (slot reopens, tokens back)
 *   6. card-yield claim + withdraw
 *   7. staking-rewards settle + withdraw
 *
 * Reads addresses from lib/contracts/addresses.local.json (generated by
 * gen-addresses.mjs) and ABIs from lib/contracts/abis.ts. Assumes trading is
 * already enabled (see scripts/dev-chain.md). Prints PASS/FAIL per flow and
 * exits non-zero on any failure.
 *
 * RUN AGAINST A FRESH DEPLOYMENT: the harness consumes the user's card and
 * stake through the forge lifecycles, so it is NOT idempotent — re-running it
 * on the same anvil state (without redeploying) will revert with
 * InsufficientFreeStake / NotCardOwner because the state it expects was already
 * mutated by the prior run. To re-verify: redeploy (dev-chain.md steps 2-4),
 * then run this once.
 *
 *   RPC_URL=http://127.0.0.1:8545 node scripts/verify-flows.mjs
 */
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  createPublicClient,
  createWalletClient,
  http,
  encodeAbiParameters,
  defineChain,
  parseEther,
  formatEther,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";

const here = dirname(fileURLToPath(import.meta.url));
const RPC = process.env.RPC_URL ?? "http://127.0.0.1:8545";

// anvil default accounts.
const DEPLOYER_PK = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"; // acct 0
const USER_PK = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"; // acct 1
const KEEPER_PK = "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"; // acct 2

const anvil = defineChain({
  id: 31337,
  name: "anvil",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: [RPC] } },
});

const { contracts } = JSON.parse(
  readFileSync(resolve(here, "../lib/contracts/addresses.local.json"), "utf8"),
);

// Load the generated ABIs (evaluate the TS `export const X = [...] as const;`).
const abisSrc = readFileSync(resolve(here, "../lib/contracts/abis.ts"), "utf8");
const abis = {};
for (const m of abisSrc.matchAll(/export const (\w+) = (\[[\s\S]*?\]) as const;/g)) {
  abis[m[1]] = JSON.parse(m[2]);
}

const pub = createPublicClient({ chain: anvil, transport: http(RPC) });
const wallet = (pk) => createWalletClient({ account: privateKeyToAccount(pk), chain: anvil, transport: http(RPC) });
const deployer = wallet(DEPLOYER_PK);
const user = wallet(USER_PK);
const keeper = wallet(KEEPER_PK);
const userAddr = privateKeyToAccount(USER_PK).address;
const deployerAddr = privateKeyToAccount(DEPLOYER_PK).address;
const keeperAddr = privateKeyToAccount(KEEPER_PK).address;

const POOL_KEY = {
  currency0: "0x0000000000000000000000000000000000000000",
  currency1: contracts.cardsToken,
  fee: 3000,
  tickSpacing: 60,
  hooks: contracts.mintHook,
};
const WAD = 10n ** 18n;

// ---- UniversalRouter V4_SWAP encoding (mirrors lib/chain/swap.ts, standard
// 5-field dialect — the LocalUniversalRouter embeds the pinned v4-periphery).
const COMMANDS_V4_SWAP = "0x10";
const ACTIONS_EXACT_IN_SETTLE_TAKE = "0x060c0f"; // SWAP_EXACT_IN_SINGLE, SETTLE_ALL, TAKE_ALL
const POOL_KEY_COMPONENTS = [
  { name: "currency0", type: "address" },
  { name: "currency1", type: "address" },
  { name: "fee", type: "uint24" },
  { name: "tickSpacing", type: "int24" },
  { name: "hooks", type: "address" },
];
// Deadline from CHAIN time, not wall-clock: the harness warps anvil forward for
// the forge flows, which would strand a Date.now()-based deadline in the past.
// (The real app uses wall clock — correct on live chains, which track it.)
const deadline = async () => (await pub.getBlock()).timestamp + 1200n;

function encodeV4SwapInput(zeroForOne, amountIn, minOut, hookData) {
  const single = encodeAbiParameters(
    [
      {
        type: "tuple",
        components: [
          { name: "poolKey", type: "tuple", components: POOL_KEY_COMPONENTS },
          { name: "zeroForOne", type: "bool" },
          { name: "amountIn", type: "uint128" },
          { name: "amountOutMinimum", type: "uint128" },
          { name: "hookData", type: "bytes" },
        ],
      },
    ],
    [{ poolKey: POOL_KEY, zeroForOne, amountIn, amountOutMinimum: minOut, hookData }],
  );
  const [cin, cout] = zeroForOne
    ? [POOL_KEY.currency0, POOL_KEY.currency1]
    : [POOL_KEY.currency1, POOL_KEY.currency0];
  const settle = encodeAbiParameters([{ type: "address" }, { type: "uint256" }], [cin, amountIn]);
  const take = encodeAbiParameters([{ type: "address" }, { type: "uint256" }], [cout, minOut]);
  return encodeAbiParameters(
    [{ type: "bytes" }, { type: "bytes[]" }],
    [ACTIONS_EXACT_IN_SETTLE_TAKE, [single, settle, take]],
  );
}

let passed = 0;
let failed = 0;
function check(name, cond, detail = "") {
  if (cond) {
    console.log(`  PASS  ${name}${detail ? ` — ${detail}` : ""}`);
    passed++;
  } else {
    console.log(`  FAIL  ${name}${detail ? ` — ${detail}` : ""}`);
    failed++;
  }
}

const read = (contract, functionName, args = []) =>
  pub.readContract({ address: contracts[contract === "token" ? "cardsToken" : contract], abi: abis[abiKey(contract)], functionName, args });

function abiKey(contract) {
  return {
    token: "cardsTokenAbi",
    cardsToken: "cardsTokenAbi",
    cardsOnChain: "cardsOnChainAbi",
    stakingVault: "stakingVaultAbi",
    cardYield: "cardYieldAbi",
    mintHook: "mintHookAbi",
    swapRouter: "universalRouterAbi",
  }[contract];
}

async function send(w, contract, functionName, args, value = 0n) {
  const { request } = await pub.simulateContract({
    account: w.account,
    address: contracts[contract === "token" ? "cardsToken" : contract],
    abi: abis[abiKey(contract)],
    functionName,
    args,
    value,
  });
  const hash = await w.writeContract(request);
  return pub.waitForTransactionReceipt({ hash });
}

async function buy(w, ethIn, recipient, withHookData) {
  const hookData = withHookData ? encodeAbiParameters([{ type: "address" }], [recipient]) : "0x";
  // Exactly what the UI signs: UniversalRouter.execute with one V4_SWAP command.
  return send(
    w,
    "swapRouter",
    "execute",
    [COMMANDS_V4_SWAP, [encodeV4SwapInput(true, ethIn, 0n, hookData)], await deadline()],
    ethIn,
  );
}

async function sell(w, tokensIn) {
  // LocalUniversalRouter pulls the input with a plain transferFrom → approve it directly.
  await send(w, "token", "approve", [contracts.swapRouter, tokensIn]);
  return send(
    w,
    "swapRouter",
    "execute",
    [COMMANDS_V4_SWAP, [encodeV4SwapInput(false, tokensIn, 0n, "0x")], await deadline()],
    0n,
  );
}

async function warp(seconds) {
  await pub.request({ method: "evm_increaseTime", params: [`0x${seconds.toString(16)}`] });
  await pub.request({ method: "evm_mine", params: [] });
}

async function main() {
  console.log(`\nverify-flows against ${RPC}\n`);
  const tradingEnabled = await read("mintHook", "tradingEnabled");
  if (!tradingEnabled) throw new Error("trading not enabled — run enableTrading first (see dev-chain.md)");

  // ---- fund the user with FORGE by buying (also flow 1) ----------------
  // Flow 1 sends the buy WITH hookData=abi.encode(keeperAddr): cards must go to
  // that EXPLICIT recipient, NOT to the signer (user) — proving explicit
  // attribution overrides the tx.origin fallback.
  console.log("Flow 1 — buy WITH hookData → mints to the specified recipient");
  const supplyBefore = await read("cardsOnChain", "totalSupply");
  const keeperCardsBefore = await read("cardsOnChain", "balanceOf", [keeperAddr]);
  await buy(user, parseEther("0.03"), keeperAddr, true); // signer=user, recipient=keeper
  const supplyAfter = await read("cardsOnChain", "totalSupply");
  const userBal = await read("token", "balanceOf", [userAddr]);
  const keeperCardsAfter = await read("cardsOnChain", "balanceOf", [keeperAddr]);
  check("buy minted new cards", supplyAfter > supplyBefore, `supply ${supplyBefore} → ${supplyAfter}`);
  check("cards went to the hookData recipient (not the signer)", keeperCardsAfter > keeperCardsBefore, `keeper balance ${keeperCardsBefore} → ${keeperCardsAfter}`);
  check("buyer (signer) kept the tokens", userBal > 0n, `${formatEther(userBal)} FORGE`);

  // Flow 1b — no hookData: the contract now falls back to tx.origin (the
  // signer), so cards mint to the USER here. This is why third-party EOA swaps
  // still deliver; our own frontend always passes the explicit address anyway.
  console.log("\nFlow 1b — buy WITHOUT hookData → mints to tx.origin (the signer)");
  const s0 = await read("cardsOnChain", "totalSupply");
  const userCardsBefore = await read("cardsOnChain", "balanceOf", [userAddr]);
  await buy(user, parseEther("0.03"), userAddr, false); // no hookData; signer=user
  const s1 = await read("cardsOnChain", "totalSupply");
  const userCardsAfter = await read("cardsOnChain", "balanceOf", [userAddr]);
  const balNoHook = await read("token", "balanceOf", [userAddr]);
  check("cards minted on a no-hookData buy", s1 > s0, `supply ${s0} → ${s1}`);
  check("cards fell back to tx.origin (the signer)", userCardsAfter > userCardsBefore, `user balance ${userCardsBefore} → ${userCardsAfter}`);
  check("buyer also received the tokens", balNoHook > userBal, "no-hookData buy still mints AND delivers tokens");

  // ---- Flow 2: sell → CardYield ----------------------------------------
  console.log("\nFlow 2 — sell → CardYield receives the 1% fee");
  const yieldBalBefore = await pub.getBalance({ address: contracts.cardYield });
  const sellAmt = 500n * WAD;
  await sell(user, sellAmt);
  const yieldBalAfter = await pub.getBalance({ address: contracts.cardYield });
  check("CardYield ETH balance grew on sell", yieldBalAfter > yieldBalBefore, `${formatEther(yieldBalBefore)} → ${formatEther(yieldBalAfter)}`);

  // ---- Flow 3: stake / unstake -----------------------------------------
  console.log("\nFlow 3 — stake / unstake");
  const stakeAmt = 6000n * WAD; // enough to forge to Legendary later
  await send(user, "token", "approve", [contracts.stakingVault, stakeAmt]);
  await send(user, "stakingVault", "stake", [stakeAmt]);
  const staked = await read("stakingVault", "stakedOf", [userAddr]);
  const free = await read("stakingVault", "freeStakeOf", [userAddr]);
  check("stakedOf reflects the stake", staked === stakeAmt, `${formatEther(staked)}`);
  check("all stake is free before forging", free === stakeAmt, `${formatEther(free)}`);
  await send(user, "stakingVault", "unstake", [1000n * WAD]);
  const stakedAfter = await read("stakingVault", "stakedOf", [userAddr]);
  check("unstake reduced the stake", stakedAfter === stakeAmt - 1000n * WAD, `${formatEther(stakedAfter)}`);

  // pick one of the user's cards (enumerate owned via ownerOf scan of ids 1..supply)
  const totalSupply = await read("cardsOnChain", "totalSupply");
  let myToken = null;
  for (let i = 1n; i <= totalSupply; i++) {
    const owner = await read("cardsOnChain", "ownerOf", [i]);
    if (owner.toLowerCase() === userAddr.toLowerCase()) {
      myToken = i;
      break;
    }
  }
  if (myToken === null) throw new Error("user owns no card to forge");

  // ---- Flow 4: forge → warp → claim ------------------------------------
  console.log(`\nFlow 4 — forge card #${myToken} → Uncommon, warp, claim`);
  const tierBefore = await read("cardsOnChain", "tierOf", [myToken]);
  await send(user, "stakingVault", "forge", [myToken, 1]); // targetTier 1 = Uncommon
  const activeId = await read("stakingVault", "activeForge", [myToken]);
  check("forge started (activeForge set)", activeId > 0n, `id ${activeId}`);
  const lockedNow = await read("stakingVault", "lockedOf", [userAddr]);
  check("stake locked while forging", lockedNow === 500n * WAD, `${formatEther(lockedNow)} locked`);
  await warp(12 * 3600 + 60); // past 12h maturation, inside 3h window
  const viewMature = await read("stakingVault", "getForge", [activeId]);
  check("forge is mature after warp", viewMature.isMature === true);
  await send(user, "stakingVault", "upgradeCard", [activeId]);
  const tierAfter = await read("cardsOnChain", "tierOf", [myToken]);
  check("card tier advanced on claim", tierAfter === 1 && tierBefore === 0, `${tierBefore} → ${tierAfter}`);
  const lockedAfterClaim = await read("stakingVault", "lockedOf", [userAddr]);
  check("stake unlocked after claim", lockedAfterClaim === 0n, `${formatEther(lockedAfterClaim)} locked`);

  // ---- Flow 5: forge → lapse → sweep -----------------------------------
  console.log(`\nFlow 5 — forge card #${myToken} → Rare, let it LAPSE, sweep`);
  const slotsBefore = await read("stakingVault", "tierSlotsRemaining", [2]); // Rare
  await send(user, "stakingVault", "forge", [myToken, 2]); // Rare
  const sweepId = await read("stakingVault", "activeForge", [myToken]);
  const slotsDuring = await read("stakingVault", "tierSlotsRemaining", [2]);
  check("target slot consumed at forge start", slotsDuring === slotsBefore - 1n, `${slotsBefore} → ${slotsDuring}`);
  await warp(24 * 3600 + 3 * 3600 + 60); // past 24h maturation AND 3h claim window
  const sweepView = await read("stakingVault", "getForge", [sweepId]);
  check("forge is sweepable after window lapses", sweepView.isSweepable === true);
  const userLockedBeforeSweep = await read("stakingVault", "lockedOf", [userAddr]);
  await send(keeper, "stakingVault", "sweep", [sweepId]); // permissionless: a DIFFERENT account
  const slotsAfterSweep = await read("stakingVault", "tierSlotsRemaining", [2]);
  const userLockedAfterSweep = await read("stakingVault", "lockedOf", [userAddr]);
  const tierUnchanged = await read("cardsOnChain", "tierOf", [myToken]);
  check("sweep reopened the slot", slotsAfterSweep === slotsBefore, `${slotsAfterSweep}`);
  check("sweep unlocked staker's tokens (not the sweeper's)", userLockedAfterSweep < userLockedBeforeSweep, `${formatEther(userLockedBeforeSweep)} → ${formatEther(userLockedAfterSweep)} locked`);
  check("card stayed at its tier after sweep", tierUnchanged === 1, `tier ${tierUnchanged}`);

  // ---- Flow 6: card-yield claim + withdraw -----------------------------
  console.log("\nFlow 6 — card-yield claim + withdraw");
  // generate some sell-fee yield first
  await sell(user, 300n * WAD);
  const accrued = await read("cardYield", "accruedOf", [myToken]);
  check("card accrued yield from sells", accrued > 0n, `${formatEther(accrued)} ETH`);
  await send(user, "cardYield", "claim", [myToken]);
  const claimable = await read("cardYield", "claimable", [userAddr]);
  check("claim moved yield to claimable", claimable > 0n, `${formatEther(claimable)} ETH`);
  const ethBefore = await pub.getBalance({ address: userAddr });
  await send(user, "cardYield", "withdraw", []);
  const claimableAfter = await read("cardYield", "claimable", [userAddr]);
  const ethAfter = await pub.getBalance({ address: userAddr });
  check("withdraw drained claimable", claimableAfter === 0n);
  check("withdraw sent ETH to the owner", ethAfter > ethBefore - parseEther("0.01"), `${formatEther(ethBefore)} → ${formatEther(ethAfter)} (net of gas)`);

  // ---- Flow 7: staking-rewards settle + withdraw -----------------------
  console.log("\nFlow 7 — staking-rewards settle + withdraw (buy fees)");
  // generate buy-fee rewards for the staker
  await buy(deployer, parseEther("0.05"), deployerAddr, true);
  const pending = await read("stakingVault", "pendingRewards", [userAddr]);
  check("staker accrued buy-fee rewards", pending > 0n, `${formatEther(pending)} ETH pending`);
  await send(user, "stakingVault", "claimRewards", []);
  const claimableStake = await read("stakingVault", "claimable", [userAddr]);
  check("settle moved rewards to claimable", claimableStake > 0n, `${formatEther(claimableStake)} ETH`);
  await send(user, "stakingVault", "withdrawRewards", []);
  const claimableStakeAfter = await read("stakingVault", "claimable", [userAddr]);
  check("withdraw drained staking claimable", claimableStakeAfter === 0n);

  console.log(`\n${passed} passed, ${failed} failed\n`);
  if (failed > 0) process.exit(1);
}

main().catch((e) => {
  console.error("\nHARNESS ERROR:", e.shortMessage ?? e.message);
  console.error(e);
  process.exit(1);
});
